### ISSUE TITLE
stray end tag and body tag open 

### ISSUE THREAD

**Issue by askaalyy** [askaalyy/masthead-semantics#1]
I am having an issue with my masthead-semantics assignment, on Markbot it keeps saying "line 7: stray end tag for head" and "line 9: start tag body seen but an element of the same type was already open." I have played around with for a while and I'm not sure what exactly is wrong. 

@hellachella 
@carolsinc

**Comment by hellachella** [comment]
There is a `"` at the end of line 6 that doesn't belong there.

**Comment by hellachella** [comment]
`  <meta name="viewport" content="width=device-width,initial-scale=1">"
`<--- culprit

remove it:
 ` <meta name="viewport" content="width=device-width,initial-scale=1">`

**Comment by askaalyy** [comment]
Thank you!
